# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e07fc023d3f6d6adcc1eb42ac1a138b7b29d1869e1f38f666b9d7a43f6dc8dd5b49498c007690be44e51d984a0a5cea35f9023cf77f0970e3fe114240919891e

test:
  secret_key_base: 04263ae690b56ae79c17809c024a86cc83671a87edb9799802e46eaac98e9499807a55b8c466aa986abb0912f7746286b595064f93ffe419135c999d8b44122f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
